### ISSUE TITLE
'GenericMeta' and '_ForwardRef' not in python3.7/typing.py

### ISSUE THREAD

**Issue by tombaker** [hsolbrig/PyShEx#17]
When I try to run https://github.com/hsolbrig/PyShEx/blob/master/tests/utils/wikidata_utils.py after installing PyShEx in my virtual environment ('shexenv'), running Python 3.7.0b2, I get
```
Traceback (most recent call last):
...
    File "/Users/tbaker/github/shexSpec/PyShEx/shexenv/lib/python3.7/site-packages/pyjsg/jsglib/typing_patch.py", line 32, in <module>
    from typing import GenericMeta, Dict, Any, List, Union, _ForwardRef
ImportError: cannot import name 'GenericMeta' from 'typing' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
```

Is this a Python 3.7 thing?

**Comment by tombaker** [comment]
Running `wikidata_utils.py` in a Python 3.6 virtualenv - no exceptions raised.

**Comment by wjordan213** [comment]
Also running into this issue

**Comment by c00kiemon5ter** [comment]
Python3.7 has the `Generic` type. Maybe, this can be used.

**Comment by lincolnq** [comment]
For those future people who find this, GenericMeta no longer exists in python 3.7 because it's not needed anymore due to PEP 560 (https://www.python.org/dev/peps/pep-0560/). For those who are migrating code, you just need to remove GenericMeta from the base class list of a metaclass. If you need backwards compatibility with python3.6 and below's typing modules, you should be able to do:

```
try:
    from typing import GenericMeta  # python 3.6
except ImportError:
    # in 3.7, genericmeta doesn't exist but we don't need it
    class GenericMeta(type): pass
```

**Comment by CaptSolo** [comment]
The issue has been fixed in the `pyjsg` module (as it occured when importing this module), the way @lincolnq suggested:

https://github.com/hsolbrig/pyjsg/blob/master/pyjsg/jsglib/__init__.py

It should no longer be a problem.
